### ISSUE TITLE
Error with Helm rendering while Instantiating composite app

### ISSUE THREAD

**Issue by BaudouinH** [open-ness/EMCO#1]
Hello.

I'm trying to deploy an app using EMCO, but EMCO fails to render the Helm manifests when instantiating the composite app. 
It fails at the rendering of the first chart of the composite app.

I'm using emcoctl and manifests to deploy everything, and I'm using images I built with the code from this repository.

I registered the clusters, created and instantiated the virtual cluster and created and approved the composite app (and its profiles and intents) with no issues.
However, when instantiating with emcoctl, I get the following error:
```
URL: projects/free5gc/composite-apps/free5gc-demo/v1/deployment-intent-groups/free5gc-deployment-intent/instantiate Response Code: 500 Response: Unable to get the sorted templates for app: Error while generating final k8s yaml: stat /tmp/k8s-ext-716707460/free5gc-control-plane: no such file or directory
```
The logs of the orchestrator give the same information:
`
{"level":"error","msg":"Unable to get the sorted templates for app: Error while generating final k8s yaml: stat /tmp/k8s-ext-961093037/free5gc-control-plane: no such file or directory","time":"2021-02-23T15:39:35Z"}
`
There are currently no other errors.

I can render the Helm archives used for the CompositeApp with `helm install test --dry-run --debug <archive>.tar.gz` with no issue.

If needed, here are the logs of the orchestrator, with a higher log verbosity ("info"):
```
{"CompositeAppHandle":"/context/3773784810858181293/","level":"info","msg":":: CreateCompositeApp ::","time":"2021-02-23T15:42:50Z"}
{"CompositeApp":"free5gc-demo","DeploymentIntentGroup":"free5gc-deployment-intent","Project":"free5gc","Release":"r1","Version":"v1","level":"info","msg":":: The meta data stored in the runtime context :: ","time":"2021-02-23T15:42:50Z"}
{"appName":"free5gc-control-plane","level":"info","msg":":: Processing App ::","time":"2021-02-23T15:42:50Z"}
{"appName":"free5gc-control-plane","level":"info","msg":":: Got the app content.. ::","time":"2021-02-23T15:42:50Z"}
{"appName":"free5gc-control-plane","level":"info","msg":":: Got the app Profile content .. ::","time":"2021-02-23T15:42:50Z"}
{"chartBasePath":"/tmp/k8s-ext-434126427","level":"info","msg":"The chartBasePath ::","time":"2021-02-23T15:42:51Z"}
{"Profile Path":"/tmp/k8s-ext-237123582","level":"info","msg":"The profile path:: ","time":"2021-02-23T15:42:51Z"}
{"level":"info","msg":"Got the profileYamlClient..","time":"2021-02-23T15:42:51Z"}
{"level":"error","msg":"Error while generating final k8s yaml","time":"2021-02-23T15:42:51Z"}
{"Dir: ":"/tmp/k8s-ext-237123582/","level":"info","msg":"Clean up k8s-ext-tmp-dir::","time":"2021-02-23T15:42:51Z"}
{"Dir: ":"/tmp/k8s-ext-434126427/","level":"info","msg":"Clean up k8s-ext-tmp-dir::","time":"2021-02-23T15:42:51Z"}
{"len(sortedTemplates):":0,"level":"info","msg":":: Total no. of sorted templates ::","time":"2021-02-23T15:42:51Z"}
10.244.0.0 - - [23/Feb/2021:15:42:50 +0000] "POST /v2/projects/free5gc/composite-apps/free5gc-demo/v1/deployment-intent-groups/free5gc-deployment-intent/instantiate HTTP/1.1" 500 160
{"level":"error","msg":"Unable to get the sorted templates for app","time":"2021-02-23T15:42:51Z"}
{"level":"error","msg":"Unable to get the sorted templates for app: Error while generating final k8s yaml: stat /tmp/k8s-ext-434126427/free5gc-control-plane: no such file or directory","time":"2021-02-23T15:42:51Z"}

```

Do you have an idea of how to proceed to debug ?

Thank you for your help

**Comment by ritusood** [comment]
Please share the emcoctl yaml file that was used for this. Can you try giving the name of the application same as the Helm chart name?

**Comment by BaudouinH** [comment]
Hello,

I used the following emcoctl yaml manifests:
```yaml
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps
metadata:
  name: {{ .CompositeApp }}
spec:
  version: v1


# creating collection composite profile entry
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/composite-profiles
metadata:
  name: {{ .CompositeProfile }}


# Adding Controller App chart and profile to the composite app
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/apps
metadata:
  name: {{ .AppController }}
file: {{ .HelmControllerApp }}
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/composite-profiles/{{ .CompositeProfile }}/profiles
metadata:
  name: {{ .ProfileControllerAppName }}
spec:
  app-name: {{ .AppController }}
file: {{ .ProfileControllerApp }}


# Adding Network configuration chart and profile to the composite app
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/apps
metadata:
  name: {{ .AppNetwork }}
file: {{ .HelmNetworkApp }}
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/composite-profiles/{{ .CompositeProfile }}/profiles
metadata:
  name: {{ .ProfileNetworkAppName }}
spec:
  app-name: {{ .AppNetwork }}
file: {{ .ProfileNetworkApp }}

# Adding test app chart and profile to the composite app
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/apps
metadata:
  name: {{ .AppUeransim }}
file: {{ .HelmUeransimApp }}
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/composite-profiles/{{ .CompositeProfile }}/profiles
metadata:
  name: {{ .ProfileUeransimName }}
spec:
  app-name: {{ .AppUeransim }}
file: {{ .ProfileUeransim }}

# Adding data plane app chart and profile to the composite app
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/apps
metadata:
  name: {{ .AppUPF }}
file: {{ .HelmUPFApp }}
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/composite-profiles/{{ .CompositeProfile }}/profiles
metadata:
  name: {{ .ProfileUPFAppName }}
spec:
  app-name: {{ .AppUPF }}
file: {{ .ProfileUPFApp }}
```
and
```yaml
# Create the deployment intent group
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups
metadata:
  name: {{ .DeploymentIntent }}
  description: smtc deployment intent group
  userData1: test1
  userData2: test2
spec:
  profile: {{ .CompositeProfile }}
  version: r1
  logical-cloud: {{ .AdminCloud }}
  override-values: []


# Create the intent in deployment intent group
---
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/deployment-intent-groups/{{.DeploymentIntent}}/intents
metadata:
  name: {{ .DeploymentIntent }}
  description: "Free5gc deployment intent"
  userData1: test1
  userData2: test2
spec:
  intent:
    genericPlacementIntent: {{ .GenericPlacementIntent }}


# Create the generic placement intent
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups/{{ .DeploymentIntent }}/generic-placement-intents
metadata:
  name: {{ .GenericPlacementIntent }}
  description: "Free5gc generic placement intent"
  userData1: test1
  userData2: test2


# Add placement intents
## UPF 
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups/{{ .DeploymentIntent }}/generic-placement-intents/{{ .GenericPlacementIntent }}/app-intents
metadata:
  name: {{ .AppEdgePlacementIntent }}
  description: "Free 5gc UPF Placement intent"
  userData1: test1
  userData2: test2
spec:
  app-name: {{ .AppEdge }}
  intent:
    allOf:
      - provider-name: {{ .ClusterProvider }}
        cluster-label-name: {{ .EdgeClusterLabel }}
##Control Plane
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups/{{ .DeploymentIntent }}/generic-placement-intents/{{ .GenericPlacementIntent }}/app-intents
metadata:
  name: {{ .AppControllerPlacementIntent }}
  description: "Free 5gc control plane Placement intent"
  userData1: test1
  userData2: test2
spec:
  app-name: {{ .AppController }}
  intent:
    allOf:
      - provider-name: {{ .ClusterProvider }}
        cluster-label-name: {{ .EdgeClusterLabel }}
## Networking
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups/{{ .DeploymentIntent }}/generic-placement-intents/{{ .GenericPlacementIntent }}/app-intents
metadata:
  name: {{ .AppNetworkPlacementIntent }}
  description: "Free 5gc control plane Placement intent"
  userData1: test1
  userData2: test2
spec:
  app-name: {{ .AppNetwork }}
  intent:
    allOf:
      - provider-name: {{ .ClusterProvider }}
        cluster-label-name: {{ .EdgeClusterLabel }}
## Ueransim
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups/{{ .DeploymentIntent }}/generic-placement-intents/{{ .GenericPlacementIntent }}/app-intents
metadata:
  name: {{ .AppUeransimPlacementIntent }}
  description: "Free 5gc control plane Placement intent"
  userData1: test1
  userData2: test2
spec:
  app-name: {{ .AppUeransim }}
  intent:
    allOf:
      - provider-name: {{ .ClusterProvider }}
        cluster-label-name: {{ .EdgeClusterLabel }}
```
And lastly:
```yaml
# Approve
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups/{{ .DeploymentIntent }}/approve

# Instantiate
---
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups/{{ .DeploymentIntent }}/instantiate
```

The Helm chart I use is still internal to my compagny so I am unable to provide it at the time.
However, I tried with another chart which I got this way:
`helm repo add stable https://charts.helm.sh/stable
"stable" has been added to your repositories
`
`helm pull stable/mysql -d <folder>`

I then replaced it on my values file, and got the same errors:
```
URL: projects/free5gc/composite-apps/free5gc-demo/v1/deployment-intent-groups/free5gc-deployment-intent/instantiate Response Code: 500 Response: Unable to get the sorted templates for app: Error while generating final k8s yaml: stat /tmp/k8s-ext-052381967/free5gc-control-plane: no such file or directory
Apply:  projects/free5gc/composite-ap`
```
Given this, I think the error may be in my emco chart manifests.

Here is the value file:
```yaml
ProjectName: free5gc
AdminCloud: free5gc-admin
LogicalCluster: free5gc-lc
ClusterProvider: cluster-provider
ClusterEdge: edge01
EdgeClusterLabel: LabelEdge
ControllerClusterLabel: LabelCloud
ClusterController: cloud01
CompositeApp: free5gc-demo
AppUPF: upf
HelmUPFApp: <folder>/free5gcdemo/mysql-1.6.9.tgz
AppController: free5gc-control-plane
HelmControllerApp: <folder>/free5gcdemo/mysql-1.6.9.tgz
AppNetwork: network-app
HelmNetworkApp: <folder>/free5gcdemo/mysql-1.6.9.tgz
AppUeransim: ueransim
HelmUeransimApp: <folder>/free5gcdemo/mysql-1.6.9.tgz
CompositeProfile: free5gc-composite-profile
ProfileUPFAppName: upf-profile
ProfileUPFApp: <folder>/collection/free5gcUserPlane_profile.tar.gz
ProfileControllerAppName: controller-app-profile
ProfileControllerApp: /<folder>/collection/free5gcControlPlane_profile.tar.gz
ProfileNetworkAppName: network-app-profile
ProfileNetworkApp: /<folder>/collection/networks5g_profile.tar.gz
ProfileUeransimName: ueransim-profile
ProfileUeransim: <folder>//collection/ueransim_profile.tar.gz
DeploymentIntent: free5gc-deployment-intent
GenericPlacementIntent: free5gc-generic-placement
AppEdgePlacementIntent: free5gc-upf-placement-intent
AppControllerPlacementIntent: free5gc-controlplane-placement-intent
AppNetworkPlacementIntent: free5gc-network-placement-intent
AppUeransimPlacementIntent: ueransim-placement-intent
KubeConfigController: <folder>/controller-config
KubeConfigEdge: <folder>/edge-config
GacIP: <ip>
GacPort: 31554
RsyncIP: <ip>
RsyncPort: 31595
```

**Comment by ritusood** [comment]
App name should match the name of the tar.gz file of the helm chart of the app. For example if tar.gz name is collectd.tar.gz then the name of the app should be collectd. In your example AppController should be mysql-1.6.9. 
We may remove this requirement in the next release if needed.

**Comment by BaudouinH** [comment]
Hello Ritu, thank you for your feedback, it solved the issue, it was indeed the name that was not matching.

I am not sure removing this requirement is needed, but indicating it in the documentation could prove useful.

Thank your for your help !

**Comment by BaudouinH** [comment]
I know have a different issue, while instantiating the apps, the following error is thrown:

```
2021-03-10 14:49:49.730588 I | Added Cluster :: edge01 through its label: LabelEdge 
2021-03-10 14:49:50.092595 I | Added Cluster :: edge01 through its label: LabelEdge 
2021-03-10 14:49:50.147198 I | Added Cluster :: edge01 through its label: LabelEdge 
2021-03-10 14:49:50.237517 I | http: panic serving 10.244.0.0:37670: runtime error: index out of range [0] with length 0
goroutine 145 [running]:
net/http.(*conn).serve.func1(0xc0006ca960)
	/usr/local/go/src/net/http/server.go:1772 +0x139
panic(0x15a41c0, 0xc000a74000)
	/usr/local/go/src/runtime/panic.go:973 +0x3e3
github.com/open-ness/EMCO/src/orchestrator/pkg/module.(*AppIntentClient).GetAllIntentsByApp(0xc0006f4e60, 0xc0004f43b0, 0x10, 0xc000907392, 0x7, 0xc0009073a9, 0xc, 0xc0009073b6, 0x2, 0xc000c1be40, ...)
	/repo/src/orchestrator/pkg/module/app_intent.go:216 +0x426
github.com/open-ness/EMCO/src/orchestrator/pkg/module.InstantiationClient.Instantiate(0x166db76, 0xc, 0x166a5a3, 0x9, 0xc000907392, 0x7, 0xc0009073a9, 0xc, 0xc0009073b6, 0x2, ...)
	/repo/src/orchestrator/pkg/module/instantiation.go:398 +0x2f60
github.com/open-ness/EMCO/src/orchestrator/api.instantiationHandler.instantiateHandler(0x1abbac0, 0xc00068c780, 0x7fc6558cc298, 0xc00046b7a0, 0xc0000feb00)
	/repo/src/orchestrator/api/instantiation_handler.go:51 +0x1cb
net/http.HandlerFunc.ServeHTTP(0xc000360da0, 0x7fc6558cc298, 0xc00046b7a0, 0xc0000feb00)
	/usr/local/go/src/net/http/server.go:2012 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0005c2240, 0x7fc6558cc298, 0xc00046b7a0, 0xc0000fe900)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x1a88620, 0xc000182008, 0x1a869e0, 0xc0005c2240, 0x1ab0b40, 0xc00094c9a0, 0xc0000fe900)
	/go/pkg/mod/github.com/gorilla/handlers@v1.3.0/handlers.go:69 +0x233
net/http.serverHandler.ServeHTTP(0xc0006c60e0, 0x1ab0b40, 0xc00094c9a0, 0xc0000fe900)
	/usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc0006ca960, 0x1ab4a80, 0xc000693900)
	/usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x35c
```

It might have to do with the way I declare the logical-clouds:
```
---
#create default logical cloud with admin permissions
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/logical-clouds
metadata:
  name: {{.AdminCloud}}
spec:
  level: "0"
---
#add cluster reference of Edge cluster to the logical cloud
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/logical-clouds/{{.AdminCloud}}/cluster-references
metadata:
  name: {{.ClusterEdge}}-lc
spec:
  cluster-provider: {{.ClusterProvider}}
  cluster-name: {{.ClusterEdge}}
  loadbalancer-ip: {{.EdgeIP}}

---
#add cluster reference of Controller cluster to the logical cloud
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/logical-clouds/{{.AdminCloud}}/cluster-references
metadata:
  name: {{.ClusterController}}-lc
spec:
  cluster-provider: {{.ClusterProvider}}
  cluster-name: {{.ClusterController}}
  loadbalancer-ip: {{.ControllerIP}}
```

With EdgeIP and ControllerIP being <ip of the master of Edge/Controller cluster>:6443
